version: "3.7"

services:
  my-apache-server:
    build:
      context: .
      dockerfile: Dockerfile.php7
    volumes:
      # - ./public-html:/usr/local/apache2/htdocs/
      - ./public-html:/var/www/html/
    ports:
      - 8080:80

  my-mysql-db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql
      - /tmp
    volumes:
      - ./db_setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
 